### ISSUE TITLE
writeCSV function does not have option to set col.names

### ISSUE THREAD

**Issue by fjshi** [cran/kutils#1]
col.names is a common parameter in other popular functions including write.table and write.csv. Although writeCSV can set row.names. it would be nice to have that option as well for col.names.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by fjshi** [comment]
> Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

Thanks. I will reach out directly to the author.
